### ISSUE TITLE
Question - Should 'offset' be renamed to 'padding' ?

### ISSUE THREAD

**Issue by phallstrom** [monterail/grape-kaminari#13]
Curious as to why 'offset' was chosen instead of 'padding' as that's the name kaminari uses?  I only came across it when I noticed the 'offset' field/documentation in my grape/swagger api docs.

If there's no reason, I'd be open to updating the gem to add the one and deprecate the other.  There's a couple of other things I was wanting to add as well...

**Comment by davidcelis** [comment]
I don't think compatibility with Kaminari's terminology should take precedence over terminology typically used by REST APIs. Kaminari was not written as a paginator for APIs, it's general purpose. Try to find an API that uses "padding" as a term instead of "offset" and I think you'll have a hard time. I don't think this should change.

**Comment by phallstrom** [comment]
@davidcelis I agree 100%, but I'd counter that typically if you see 'offset' you also see 'limit'.  'offset/limit' or 'page/per'.  It feels so weird to have 'page, per_page, and offset' since 'offset' isn't being used in the standard way (ie. the SQL way).

I'd honestly forgotten about this entirely so must not be that important to me and I guess no one else feels strongly.  Still feels weird to me though :)

**Comment by teamon** [comment]
Sorry for not being very active in this thread...

I don't feel we should change it now, so I'm going to close this issue for now. (Let me know if any of you are still interested in this)
